config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
    authority: # http://test5-st-authserver
    requireHttpsMetadata: # "false"
    isOnK8s: # "true"
    metaAddress: # http://test5-st-authserver
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: # test5-st-public-web
  tlsSecret: test5-tls

image:
  repository: mycompanyname/test5-app-public-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}